#!/usr/bin/env python3
# extract_block_ranges 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# See https://documentation.dnanexus.com/developer for documentation and
# tutorials on how to modify this file.
#
# DNAnexus Python Bindings (dxpy) documentation:
#   http://autodoc.dnanexus.com/bindings/python/current/

import os
import dxpy

@dxpy.entry_point('main')
def main(block_pos, out_ranges, block_id):

    # The following line(s) initialize your data object inputs on the platform
    # into dxpy.DXDataObject instances that you can start using immediately.

    block_pos = dxpy.DXFile(block_pos)
    out_ranges = dxpy.DXFile(out_ranges)

    # The following line(s) download your file inputs to the local file system
    # using variable names for the filenames.

    dxpy.download_dxfile(block_pos.get_id(), "block_pos")

    dxpy.download_dxfile(out_ranges.get_id(), "out_ranges")
    
    # Fill in your application code here.
    block_pos = open("block_pos", 'r')
    lines = block_pos.readlines()
    if lines:
        first = lines[0]
        last = lines[-1]
    
    
    out = open("out_ranges", "a")
        
    block_start_end = [block_id, first.rstrip("\n"), last.rstrip("\n")]
    print("\t".join(block_start_end), file=out)
    out.close()
    
    # The following line(s) use the Python bindings to upload your file outputs
    # after you have created them on the local file system.  It assumes that you
    # have used the output field name for the filename for each output, but you
    # can change that behavior to suit your needs.

    outfile = dxpy.upload_local_file("out_ranges")

    # The following line fills in some basic dummy output and assumes
    # that you have created variables to represent your output with
    # the same name as your output fields.

    output = {}
    output["outfile"] = dxpy.dxlink(outfile)

    return output

dxpy.run()
